### ISSUE TITLE
Modification of the ARM Template for Storage

### ISSUE THREAD

**Issue by SyntaxC4** [azure-appservice-samples/ContosoMoments#22]
To set up your site, set the connection string MS_AzureStorageAccountConnectionString to your storage connection string. See https://github.com/lindydonna/ContosoMoments/blob/master/src/Cloud/ContosoMoments.API/Web.config#L15

**Comment by lindydonna** [comment]
Fixed in b40338fba5e980aefdf47f4a9b87f726db751161.
