### ISSUE TITLE
Image re-size webjob is synchronous

### ISSUE THREAD

**Issue by yochay** [azure-appservice-samples/ContosoMoments#34]
There are 4 await functions each re-sizing an image. The actual resizing happen synchronously. One way to solve it is to have the webjob resize only one image, and select the image size and blob path via the info in the Q message

**Comment by lindydonna** [comment]
I could also just start each resize operation on its own thread, using Task.Start.

**Comment by SyntaxC4** [comment]
We are removing the WebJob, and making it an Azure Function which uses a blob trigger. We could have sent multiple message on the queue to ensure the resized happened in parallel, but it's a moot point now.
