### ISSUE TITLE
Remove duplicate azuredeploy.json

### ISSUE THREAD

**Issue by lindydonna** [azure-appservice-samples/ContosoMoments#39]
There's one in the root and in the deployment folder. We should use only one, and have the deployment folder reference the one at the root.

**Comment by SyntaxC4** [comment]
@lindydonna This is as designed as we want to make sure that we have a project for the ARM Template as there is some great tooling available to test and modify the templates. The azuredeploy.json is required in the root for the Deploy to Azure button to function.

What I would prefer is to change the task of this to "Add Post Build step to copy ARM template to the repository root"

**Comment by lindydonna** [comment]
I have a PR that uses the root file in the VS project, and it works fine. I removed the version in the deployment folder.  That seems simpler than a post build step, no?

**Comment by lindydonna** [comment]
Fixed in  b40338fb.
