### ISSUE TITLE
Deploy to Azure fails

### ISSUE THREAD

**Issue by nzthiago** [azure-appservice-samples/ContosoMoments#85]
Trying to use the Deploy to Azure button from my unmodified fork. Regardless of what I use in the Resource Group and Hosting Plan name values it always fails with a validation error saying the Notification Hub name is trademarked or reserved word. I tried a few different and unrelated names. Here's the validation error printscreen:
<img width="420" alt="screen shot 2017-01-10 at 7 38 56 am" src="https://cloud.githubusercontent.com/assets/1563288/21796376/b4875c04-d708-11e6-87d9-b9348dc3fcf7.png">

**Comment by manvekar** [comment]
I too face the same exact problem mentioned by nzthiago 
![capture](https://cloud.githubusercontent.com/assets/10297060/21840598/4cbf1952-d804-11e6-8c3a-bdd6e2166b67.PNG)

**Comment by nzthiago** [comment]
It seems to actually deploy the resources, but this error makes it not continue from the ARM template deploy perspective; I only noticed later that it did run the deploy... I tried figuring out why and for some reason I think it doesn't like "microsoft' in the name field of the links section, which is odd as that used to work as far as I know

**Comment by lindydonna** [comment]
@manvekar This is really weird, and it looks like some validation is happening that did not previously. In order for the Mobile Apps blade to see the linked reference, that is the name that the link name is supposed to have. I'll follow up with the ARM team to see what's going on.

**Comment by lindydonna** [comment]
@nzthiago and @manvekar I checked with the ARM team and they were already aware of the issue and have deployed a fix. Can you try again?

**Comment by nzthiago** [comment]
Success!

![screen shot 2017-02-09 at 9 54 53 am](https://cloud.githubusercontent.com/assets/1563288/22796118/0597eb56-eeae-11e6-99ed-123a2702df41.png)
