### ISSUE TITLE
missing node_modules\azure-mobile-apps-client folder

### ISSUE THREAD

**Issue by hoiwailone** [azure-appservice-samples/ContosoMoments#87]
Dear Madam,

The project is missing reference folder to 
ContosoMoments-master\src\Cloud\ContosoMoments.API\app\node_modules\azure-mobile-apps-client

could you please check it ? 
we have facing issue to call the javascript.

thanks,

**Comment by lindydonna** [comment]
You need to restore npm packages before building.
